### ISSUE TITLE
Liste des collaborateurs - pas d'image par défaut

### ISSUE THREAD

**Issue by roddet** [etbourreau/sirh-gestion-personnel#2]
**Scénario** :
* Créer un nouveau collaborateur
* Se rendre sur la page de liste des collaborareurs

**Résultat obtenu** :
* pas d'image par défaut pour le nouveau collaborateur

**Résultat attendu** :
* Le nouveau collaborateur possède une image par défaut.

**Comment by etbourreau** [comment]
default pic added and managed
