### ISSUE TITLE
API REST - Type Date Java 8 en JSON

### ISSUE THREAD

**Issue by roddet** [etbourreau/sirh-gestion-personnel#3]
**Scénario**
* Invoquer l'API `GET /api/collaborateurs`

**Résultat obtenu**
* Le format Date suivant
` "dateNaissance": {
            "year": 1992,
            "month": "MARCH",
            "chronology": {
                "calendarType": "iso8601",
                "id": "ISO"
            },
            "era": "CE",
            "dayOfYear": 81,
            "dayOfWeek": "SATURDAY",
            "leapYear": true,
            "dayOfMonth": 21,
            "monthValue": 3
        },
`

**Résultat attendu**
* la date au format ISO (`2017-12-01`).

**Comment by etbourreau** [comment]
Java8 Dates provider added
